In [1]:
from mvp_simplex_env import SimplexWalker

In [2]:
import torch


In [23]:

# Assume these parameters are defined in your environment instance:
min_incr = 0.01
n_dim = 4
dummy_float = torch.float32
device = "cpu"

# Create an instance of your environment with dummy parameters
# (adjust the __init__ as needed if you require additional kwargs)
env = SimplexWalker(min_incr=min_incr, n_dim=n_dim,
                    device=device, float_precision=dummy_float)

# Create a dummy state tensor that is a batch of two states.
# For example, let your states be in the range [0,1]
states = torch.tensor([[0.2, 0.3, 0.1, 0.4],
                       [0.5, 0.2, 0.1, 0.2]], dtype=dummy_float, device=device)
one_hot = torch.tensor([[0.0, 1, 0.0, 0.0],
                       [0.0, 1, 0.0, 0.0]], dtype=dummy_float, device=device)

# Create dummy relative increments that come from the Beta distribution.
# Here we simulate an output in [0,1].
increments_rel = torch.tensor([[0.5, 0.2, 0.8, 0.1],
                               [0.3, 0.4, 0.6, 0.7]], dtype=dummy_float, device=device)





In [21]:

abs_increments_forward = env.relative_to_absolute_increments(
    states, increments_rel, one_hot, is_backward=False)

In [22]:
abs_increments_forward

tensor([[0.0000, 0.0080, 0.0000, 0.0000],
        [0.0000, 0.0060, 0.0000, 0.0000]])

In [8]:
def test_jacobian(is_backward: bool):
    # We'll take a dummy state tensor. For backward, make sure states are away from min_incr.
    # For instance:
    dummy_state = torch.tensor([[0.2, 0.3, 0.1, 0.4],
                                [0.5, 0.2, 0.1, 0.2]], dtype=dummy_float, device=device)

    jacobian_diag = env._get_jacobian_diag(
        dummy_state, is_backward=is_backward)
    print(f"Jacobian diagonal (is_backward={is_backward}):\n", jacobian_diag)



# Test for forward update
test_jacobian(is_backward=False)
# Test for backward update
test_jacobian(is_backward=True)

Jacobian diagonal (is_backward=False):
 tensor([[-100.],
        [-100.]])
Jacobian diagonal (is_backward=True):
 tensor([[1.0101],
        [1.0101]])


In [25]:
env.reset()

In [19]:
env.state

[0.041886106133461, 0.0, 0.7543605342507362, 0.19993228651583195]

In [29]:
for i in range (100):
    env.reset()
    env.trajectory_random()
    print(env.state)

[0.21422365307807922, 0.649525485932827, 0.08914194256067276, 0.04578368738293648]
[0.31545567885041237, 0.16315348539501429, 0.5203205943107605, 0.0]
[0.5596168041229248, 0.274801105260849, 0.10854043811559677, 0.0]
[0.7606562003493309, 0.0, 0.2138291299343109, 0.015516550280153751]
[0.36419782042503357, 0.014710457995533943, 0.05534982681274414, 0.5600257348269224]
[0.18328261375427246, 0.0, 0.8022097833454609, 0.011755822226405144]
[0.1263224482536316, 0.36482954025268555, 0.05258575826883316, 0.3345494270324707]
[0.0, 0.2580142766237259, 0.0, 0.6094865798950195]
[0.5389794707298279, 0.0, 0.0, 0.0]
[0.0, 0.37659558467566967, 0.4821424335241318, 0.13427971303462982]
[0.09420409798622131, 0.3544558072462678, 0.029557254165410995, 0.5166248679161072]
[0.5500265955924988, 0.09784823656082153, 0.033467886969447136, 0.31530317664146423]
[0.31319117546081543, 0.01763339713215828, 0.0563066229224205, 0.6095254346728325]
[0.5018162727355957, 0.0, 0.011899759992957115, 0.4851088225841522]
[0.